name: Build macOS App

on:
  release:
    types: [published]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install briefcase toml

      - name: Build macOS app
        run: |
          briefcase create macOS
          briefcase build macOS
          briefcase package macOS

      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macOS-app
          path: dist/macOS
